project:
  type: website
  output-dir: docs

website: 
  title: "R Quick Reference"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - websiteaim.qmd
      - level1commands.qmd
      - level2commands.qmd
      - mcq.qmd
      - references.qmd

format:
  html:
    theme: litera
    css: styles.css
    toc: true

editor: visual


